channels:
- conda-forge
dependencies:
- python=3.10.12
- pip<=23.2.1
- pip:
  - mlflow==2.7.1
  - cloudpickle==2.2.1
  - lz4==4.3.2
  - numpy==1.24.4
  - packaging==23.1
  - psutil==5.9.5
  - pyyaml==6.0.1
  - scikit-learn==1.3.1
  - scipy==1.11.3
name: mlflow-env
